### ISSUE TITLE
Delete annotation

### ISSUE THREAD

**Issue by charleygros** [biigle/community-scripts#3]
Hi there,

Thanks for the very useful scripts.
I am trying to adapt `convert-laser-points.py` to my application and have a question:
I have changed the shape of a given annotation (eg from circle to point), I now would like to delete the old annotation (eg the circle). How would you delete an annotation?

I tried something like:
```
                    api.delete('images/{}/annotations/{}'.format(image_id, annotation_id))
```
without much success

Many thanks in advance!

**Comment by charleygros** [comment]
Related question: how to delete a `laserpoint`? I had a try with:
```
        laser_info = api.get('images/{}/laserpoints'.format(image_id)).json()
```
But no success either

**Comment by mzur** [comment]
Annotations can be deleted using the [delete annotations endpoint](https://biigle.de/doc/api/index.html#api-Annotations-DestroyAnnotation) and the annotation ID. You can also [update an existing annotation](https://biigle.de/doc/api/index.html#api-Annotations-UpdateAnnotation) and change the shape as well as points to convert it from a circle to a point.

Currently, detected laser points cannot be deleted. You could update them by running a manual laser point detection using existing annotations that you can modify.

**Comment by charleygros** [comment]
Many thanks for your prompt and helpful answer @mzur ! Really appreciated.

I was trying to (i) `api.post` (ii) `api.delete` whereas.... as you said... I can directly use `api.put`.
I ve just tried and it works beautifully! Many thanks again!

Another related question: can you do batch processing with `api.put`, in a same way as `api.post`, eg [here](https://github.com/biigle/community-scripts/blob/master/convert-laser-points/convert-laser-points.py#L61).

**Comment by mzur** [comment]
No, batch updating of annotations is not available. I would accept a pull request that implements this, though. Or you create a feature request and it might be implemented sometime in the future. Please see our [contributing guide](https://github.com/biigle/core/blob/master/CONTRIBUTING.md) for more information.

**Comment by charleygros** [comment]
It looks to run quite okay without batch processing for my current application, I was being curious.
Thanks again @mzur. I am closing the issue.
