### ISSUE TITLE
CoralNet & BIIGLE data integration

### ISSUE THREAD

**Issue by charleygros** [biigle/community-scripts#4]
Hi @mzur,

We used two platforms to label our data: CoralNet for habitat forming structures (eg coral reef) and BIIGLE for more discrete organisms (eg anemones, octocorals) --> two different Point Processes.
We aim at combining these data into a multi-species distribution model and are currently thinking of how to better perform this data integration.

I was wondering if you had any recommendation about this? or if you were aware of some published studies that faced the same challenge?

Cheers,
Charley

**Comment by mzur** [comment]
What do you mean by "multi-species distribution model" exactly? Some kind of machine learning model? Or a collection of multi-species image annotations?

**Comment by charleygros** [comment]
Oh, to model the spatial distribution of some benthic community --> use the biological data (count, abundance etc from BIIGLE & CoralNet) and environmental data (eg depth, salinity), to predict the abundance of such species in locations that have not been sampled yet.
Examples of models: [HMSC](https://github.com/hmsc-r/HMSC), [boral](https://github.com/cran/boral), [RCP](https://github.com/skiptoniam/ecomix).

**Comment by mzur** [comment]
I see. So you are looking for a way to combine the point annotation data that you collected with BIIGLE and CoralNet to use it as input/training data for your spatial distribution model? BIIGLE offers a [CSV image annotation report](https://biigle.de/manual/tutorials/reports/reports-schema#annotation-csv-report) that you can use for further (offline) processing of your annotation data. I'm not familiar with CoralNet but they surely offer a similar data export. You should be able to combine the BIIGLE report with the CoralNet export and other environmental data using a simple script, excel or basic command line instructions.

**Comment by charleygros** [comment]
Thanks for your answer @mzur !

> So you are looking for a way to combine the point annotation data that you collected with BIIGLE and CoralNet to use it as input/training data for your spatial distribution model?

Yes correct!

> BIIGLE offers a CSV image annotation report that you can use for further (offline) processing of your annotation data.

Yes, this annotation report is really really convenient, thanks for that!!

> I'm not familiar with CoralNet but they surely offer a similar data export.

Yes you are correct they do.

The Thing is the annotation process in CoralNet and in BIIGLE is not the same, see below: in CoralNet you label the 108 pixels indicated with a cross and that's it, whereas on BIIGLE you label everything you can possibly see.
![image](https://user-images.githubusercontent.com/14353425/93147665-2e47b480-f735-11ea-95c9-be1d541c80c3.png)

--> it implies that the two dataset were generated with different sampling processes and have data currency --> We have to be careful in how we combine these datasets for this reason.

This "Data integration" is an active field of research atm, eg [Miller et al 2019](https://besjournals.onlinelibrary.wiley.com/doi/epdf/10.1111/2041-210X.13110?saml_referrer) or [Fletcher et al 2019](https://esajournals.onlinelibrary.wiley.com/doi/epdf/10.1002/ecy.2710).

.

**Comment by mzur** [comment]
I'm not familiar with methods for data integration so I can't give any advice in that regard. I can only mention that BIIGLE also offers a [regular sampling](https://biigle.de/manual/tutorials/annotations/navigating-images#regular-sampling) mode for image annotation but we recommend the random sampling method, instead, because regular sampling has the potential to introduce a systematic error.

**Comment by charleygros** [comment]
Thanks @mzur .

Could you please explain what you meant by:

>  If your images show a specific pattern with a fixed frequency, you might introduce a systematic error due to spatial aliasing.

**Comment by mzur** [comment]
Suppose you have a pattern that occurs at regular intervals with a spacing that happens to match the regular sampling locations (red bars):

![aliasing](https://user-images.githubusercontent.com/2457311/93325947-6673f380-f818-11ea-9e31-b01c3105a361.jpg)

In this example, you would estimate that 100% of the image content is taken up by whatever the pattern represents. If the pattern is shifted a little bit, you might end up with a 0% estimate. Both are incorrect. It may be very unlikely to encounter such a thing in a real environment but the potential is there. You wouldn't have these issues with random sampling.

**Comment by charleygros** [comment]
Crystal clear! Many thanks @mzur !
I think we can close this issue for now, thanks again.
